/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bus.ChairBUS;
import bus.ChairTypeBUS;
import bus.MovieBUS;
import bus.MovieTimesBUS;
import bus.RoomBUS;
import bus.ShowtimesBUS;
import bus.TicketBUS;
import bus.UserBUS;
import dao.MovieDAO;
import dao.MovieTimesDAO;
import dao.RoomDAO;
import dto.ChairDTO;
import dto.ChairTypeDTO;
import javax.swing.DefaultComboBoxModel;
import dto.MovieDTO;
import dto.MovieTimesDTO;
import dto.RoomDTO;
import dto.ShowtimesDTO;
import dto.TicketDTO;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ngọc Anh
 */
public class JFrameMainNv extends javax.swing.JFrame {

    private ChairBUS chairBUS = new ChairBUS();
    private ShowtimesBUS showtimesBUS = new ShowtimesBUS();
    private UserBUS userBUS = new UserBUS();
    private TicketBUS ticketBUS = new TicketBUS();
    private ChairTypeBUS chairTypeBUS = new ChairTypeBUS();
    private RoomBUS roomBUS = new RoomBUS();
    private MovieBUS movieBUS = new MovieBUS();
    private MovieTimesBUS movieTimesBUS = new MovieTimesBUS();
    
    /**
     * Creates new form JFrameMain
     */
    public JFrameMainNv() {
        initComponents();
        jPanelQLThongTin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelQLThongTin = new javax.swing.JPanel();
        btPhim = new javax.swing.JButton();
        btLichChieu = new javax.swing.JButton();
        btGhe = new javax.swing.JButton();
        btQuanLyThongTin = new javax.swing.JButton();
        btXemLichChieu = new javax.swing.JButton();
        btBanVe = new javax.swing.JButton();
        btTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình quản lý bán vé xem phim");
        setLocation(new java.awt.Point(200, 100));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ BÁN VÉ XEM PHIM");

        jPanelQLThongTin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btPhim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btPhim.setText("Phim");
        btPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPhimActionPerformed(evt);
            }
        });

        btLichChieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLichChieu.setText("Lịch chiếu");
        btLichChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLichChieuActionPerformed(evt);
            }
        });

        btGhe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btGhe.setText("Ghế");
        btGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQLThongTinLayout = new javax.swing.GroupLayout(jPanelQLThongTin);
        jPanelQLThongTin.setLayout(jPanelQLThongTinLayout);
        jPanelQLThongTinLayout.setHorizontalGroup(
            jPanelQLThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLThongTinLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(btLichChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(btGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelQLThongTinLayout.setVerticalGroup(
            jPanelQLThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLThongTinLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanelQLThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btGhe, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btLichChieu, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        btQuanLyThongTin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btQuanLyThongTin.setText("Quản lý thông tin");
        btQuanLyThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuanLyThongTinActionPerformed(evt);
            }
        });

        btXemLichChieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btXemLichChieu.setText("Xem lịch chiếu");
        btXemLichChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemLichChieuActionPerformed(evt);
            }
        });

        btBanVe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btBanVe.setText("Bán vé");
        btBanVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanVeActionPerformed(evt);
            }
        });

        btTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btTimKiem.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btQuanLyThongTin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btXemLichChieu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBanVe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btTimKiem))
                            .addComponent(jPanelQLThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQuanLyThongTin)
                    .addComponent(btXemLichChieu)
                    .addComponent(btBanVe)
                    .addComponent(btTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelQLThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btXemLichChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemLichChieuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btXemLichChieuActionPerformed

    private void btQuanLyThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuanLyThongTinActionPerformed
          jPanelQLThongTin.setVisible(true);
    }//GEN-LAST:event_btQuanLyThongTinActionPerformed

    private void btBanVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanVeActionPerformed
        jPanelQLThongTin.setVisible(false);
        JFrameBanVe jFrameBanVe = new JFrameBanVe();
        DefaultComboBoxModel cbBoxModel = new DefaultComboBoxModel();
        for(ChairDTO chair : chairBUS.findAll()){
            cbBoxModel.addElement(chair.getChairCode());
        }
        jFrameBanVe.getCbMaGhe().setModel(cbBoxModel);
        DefaultComboBoxModel cbBoxModelMaLC = new DefaultComboBoxModel();
        for(ShowtimesDTO p : showtimesBUS.findAll()){
            cbBoxModelMaLC.addElement(p.getShowTimesCode());
        }
        jFrameBanVe.getCbMaLichChieu().setModel(cbBoxModelMaLC);
        jFrameBanVe.getTxtUserId().setText(txtUserId.getText()); 
        DefaultTableModel model = (DefaultTableModel) jFrameBanVe.getjTable1().getModel();
        for(TicketDTO ticket : ticketBUS.findAll()){
            model.addRow(new Object[]{ticket.getId(), chairBUS.findById(ticket.getChairId()).getChairCode(),
            showtimesBUS.findById(ticket.getShowtimesId()).getShowTimesCode(), userBUS.findById(ticket.getUserId()).getUserCode()});
        }
        jFrameBanVe.setVisible(true);
        
    }//GEN-LAST:event_btBanVeActionPerformed

    private void btGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGheActionPerformed
        // TODO add your handling code here:
        JFrameQLGhe jFrameQLGhe = new JFrameQLGhe();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(ChairTypeDTO p : chairTypeBUS.findAll()){
            model.addElement(p.getChairTypeCode());
        }
        jFrameQLGhe.getCbLoaiGhe().setModel(model);
        DefaultTableModel tableModel = (DefaultTableModel) jFrameQLGhe.getjTable().getModel();
        for(ChairDTO chair : chairBUS.findAll()){
            tableModel.addRow(new Object[]{chair.getId(),chair.getChairCode(),
                chair.getStatus(),chairTypeBUS.findById(chair.getChairTypeId()).getChairTypeCode()});
        }
        jFrameQLGhe.setVisible(true);
    }//GEN-LAST:event_btGheActionPerformed

    private void btLichChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLichChieuActionPerformed
        // TODO add your handling code here:
        JFrameQLLichChieu jFrameQLLichChieu = new JFrameQLLichChieu();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(MovieTimesDTO m : movieTimesBUS.findAll()){
            model.addElement(m.getMovieTimesCode());
        }
        jFrameQLLichChieu.getCaChieu().setModel(model);
        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        for(MovieDTO movie : movieBUS.findAll()){
            model1.addElement(movie.getMovieCode());
        }
        jFrameQLLichChieu.getCbPhim().setModel(model1);
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        for(RoomDTO room : roomBUS.findAll()){
            model2.addElement(room.getRoomCode());
        }
        jFrameQLLichChieu.getCbRoom().setModel(model2);
        DefaultTableModel tableModel = (DefaultTableModel) jFrameQLLichChieu.getjTable().getModel();
        ArrayList<ShowtimesDTO> showtimes = showtimesBUS.findAll();
        for(ShowtimesDTO s : showtimes){
            RoomDTO room = roomBUS.findById(s.getRoomId());
            MovieDTO movie = movieBUS.findById(s.getMovieId());
            MovieTimesDTO movieTimesDTO = movieTimesBUS.findById(s.getMovieTimesId());
            tableModel.addRow(new Object[]{s.getId(), s.getShowTimesCode(), s.getProjectionDate(),
                movieTimesDTO.getMovieTimesCode(), room.getRoomCode(), movie.getMovieCode()});

        }
        jFrameQLLichChieu.getjTable().setModel(tableModel);
        jFrameQLLichChieu.setVisible(true);
    }//GEN-LAST:event_btLichChieuActionPerformed

    private void btPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPhimActionPerformed
        // TODO add your handling code here:
        JFrameQLPhim jFrameNhapPhim = new JFrameQLPhim();
        DefaultTableModel model = (DefaultTableModel) jFrameNhapPhim.getjTable().getModel();
        ArrayList<MovieDTO> movies = movieBUS.findAll();
        for (MovieDTO movie : movies) {
            model.addRow(new Object[]{movie.getId(), movie.getMovieCode(),
                movie.getMovieName(),movie.getCategory(), movie.getTime(),
                movie.getProducer(), movie.getShortDescription()});
        }
        jFrameNhapPhim.setVisible(true);
    }//GEN-LAST:event_btPhimActionPerformed

    @SuppressWarnings("FieldMayBeFinal")
    private JTextField txtUserId = new JTextField();
    public JTextField getTxtUserId(){
        return txtUserId;
    }
    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMainNv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMainNv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMainNv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMainNv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameMainNv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBanVe;
    private javax.swing.JButton btGhe;
    private javax.swing.JButton btLichChieu;
    private javax.swing.JButton btPhim;
    private javax.swing.JButton btQuanLyThongTin;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXemLichChieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelQLThongTin;
    // End of variables declaration//GEN-END:variables
}